# Generated by Django 3.2 on 2023-05-24 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(2023, message='Год выпуска не должен быть в будущем времени')], verbose_name='Год выпуска'),
        ),
    ]
