# Generated by Django 3.2 on 2023-05-15 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[\\w.@+-]+\\z')], verbose_name='никнейм пользователя'),
        ),
    ]
