# Generated by Django 3.2 on 2023-05-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230524_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitleGenre',
        ),
    ]
