# Generated by Django 3.2 on 2023-05-24 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_delete_titlegenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1, 'Оценка должна быть от 1 до 10'), django.core.validators.MaxValueValidator(10, 'Оценка должна быть от 1 до 10')]),
        ),
    ]
